# Generated by Django 4.2.7 on 2023-11-16 12:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenplaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=10000, verbose_name='enter description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=10000, verbose_name='enter description'),
        ),
    ]
