# Generated by Django 4.2.7 on 2023-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenplaner', '0003_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='name'),
        ),
    ]
